/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Calculator;

/**
 *
 * @author Turan
 */
public class Calculator extends javax.swing.JFrame {

    /**
     * Creates new form Calculator
     */
    
    double NumEnter1;
    double NumEnter2;
    double Result;
    String Op;
    
    public Calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")


    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtxtResult = new javax.swing.JTextField();
        multibtn = new javax.swing.JButton();
        pointbtn = new javax.swing.JButton();
        twobtn = new javax.swing.JButton();
        threebtn = new javax.swing.JButton();
        onebtn = new javax.swing.JButton();
        equalbtn = new javax.swing.JButton();
        dividedbtn = new javax.swing.JButton();
        fourbtn = new javax.swing.JButton();
        fivebtn = new javax.swing.JButton();
        sixbtn = new javax.swing.JButton();
        minusbtn = new javax.swing.JButton();
        sevenbtn = new javax.swing.JButton();
        eightbtn = new javax.swing.JButton();
        ninebtn = new javax.swing.JButton();
        plusebtn = new javax.swing.JButton();
        backbtn = new javax.swing.JButton();
        cebtn = new javax.swing.JButton();
        cbtn = new javax.swing.JButton();
        pluseminusbtn = new javax.swing.JButton();
        zerobtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtxtResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtResultActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 270, 40));

        multibtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        multibtn.setText("*");
        multibtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multibtnActionPerformed(evt);
            }
        });
        getContentPane().add(multibtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 60, 60));

        pointbtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        pointbtn.setText(".");
        pointbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pointbtnActionPerformed(evt);
            }
        });
        getContentPane().add(pointbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 60, 60));

        twobtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        twobtn.setText("2");
        twobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twobtnActionPerformed(evt);
            }
        });
        getContentPane().add(twobtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 60, 60));

        threebtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        threebtn.setText("3");
        threebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threebtnActionPerformed(evt);
            }
        });
        getContentPane().add(threebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 60, 60));

        onebtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        onebtn.setText("1");
        onebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onebtnActionPerformed(evt);
            }
        });
        getContentPane().add(onebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 60, 60));

        equalbtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        equalbtn.setText("=");
        equalbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equalbtnActionPerformed(evt);
            }
        });
        getContentPane().add(equalbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, 60, 60));

        dividedbtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        dividedbtn.setText("/");
        dividedbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dividedbtnActionPerformed(evt);
            }
        });
        getContentPane().add(dividedbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, 60, 60));

        fourbtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        fourbtn.setText("4");
        fourbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourbtnActionPerformed(evt);
            }
        });
        getContentPane().add(fourbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 60, 60));

        fivebtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        fivebtn.setText("5");
        fivebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fivebtnActionPerformed(evt);
            }
        });
        getContentPane().add(fivebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 60, 60));

        sixbtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        sixbtn.setText("6");
        sixbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixbtnActionPerformed(evt);
            }
        });
        getContentPane().add(sixbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 60, 60));

        minusbtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        minusbtn.setText("-");
        minusbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minusbtnActionPerformed(evt);
            }
        });
        getContentPane().add(minusbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 60, 60));

        sevenbtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        sevenbtn.setText("7");
        sevenbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sevenbtnActionPerformed(evt);
            }
        });
        getContentPane().add(sevenbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 60, 60));

        eightbtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        eightbtn.setText("8");
        eightbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eightbtnActionPerformed(evt);
            }
        });
        getContentPane().add(eightbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 60, 60));

        ninebtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ninebtn.setText("9");
        ninebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ninebtnActionPerformed(evt);
            }
        });
        getContentPane().add(ninebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 60, 60));

        plusebtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        plusebtn.setText("+");
        plusebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusebtnActionPerformed(evt);
            }
        });
        getContentPane().add(plusebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 60, 60));

        backbtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        backbtn.setText(" ←");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });
        getContentPane().add(backbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 60, 60));

        cebtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cebtn.setText("CE");
        getContentPane().add(cebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 60, 60));

        cbtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cbtn.setText("C");
        cbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbtnActionPerformed(evt);
            }
        });
        getContentPane().add(cbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 60, 60));

        pluseminusbtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        pluseminusbtn.setText("±");
        pluseminusbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pluseminusbtnActionPerformed(evt);
            }
        });
        getContentPane().add(pluseminusbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 60, 60));

        zerobtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        zerobtn.setText("0");
        zerobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zerobtnActionPerformed(evt);
            }
        });
        getContentPane().add(zerobtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 60, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void EnterNumbers(String q) {
        String nums = jtxtResult.getText()+q;
        jtxtResult.setText(nums);
    }
    
    private void jtxtResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtResultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtResultActionPerformed

    private void threebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threebtnActionPerformed
         EnterNumbers("3");
    }//GEN-LAST:event_threebtnActionPerformed

    private void multibtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multibtnActionPerformed
        NumEnter1 = Double.parseDouble(jtxtResult.getText());
        jtxtResult.setText("");
        Op = "*";
    }//GEN-LAST:event_multibtnActionPerformed

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        String backSp = null;
        if(jtxtResult.getText().length() > 0)
        {
            StringBuilder sb = new StringBuilder(jtxtResult.getText());
            sb.deleteCharAt(jtxtResult.getText().length() - 1);
            backSp = sb.toString();
            jtxtResult.setText(backSp);
            
        }
    }//GEN-LAST:event_backbtnActionPerformed

    private void cbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbtnActionPerformed
        jtxtResult.setText("");
        String Fn, Sn;
        Fn = String.valueOf(NumEnter1);
        Sn = String.valueOf(NumEnter2);
        
        Fn = "";
        Sn = "";
    }//GEN-LAST:event_cbtnActionPerformed

    private void zerobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zerobtnActionPerformed
         EnterNumbers("0");
    }//GEN-LAST:event_zerobtnActionPerformed

    private void equalbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equalbtnActionPerformed
        NumEnter2 = Double.parseDouble(jtxtResult.getText());
        if(Op == "+")
        {
            Result = NumEnter1 + NumEnter2;
            jtxtResult.setText(String.valueOf(Result));
        }
        else if(Op == "-")
            {
                   Result = NumEnter1 - NumEnter2;
                   jtxtResult.setText(String.valueOf(Result));
            }
        else if(Op == "*")
        {
            Result = NumEnter1 * NumEnter2;
            jtxtResult.setText(String.valueOf(Result));
        }
        else if(Op == "/")
        {
            Result = NumEnter1 / NumEnter2;
            jtxtResult.setText(String.valueOf(Result));
        }
    }//GEN-LAST:event_equalbtnActionPerformed

    private void dividedbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dividedbtnActionPerformed
        NumEnter1 = Double.parseDouble(jtxtResult.getText());
        jtxtResult.setText("");
        Op = "/";
    }//GEN-LAST:event_dividedbtnActionPerformed

    private void sixbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixbtnActionPerformed
         EnterNumbers("6");
    }//GEN-LAST:event_sixbtnActionPerformed

    private void ninebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ninebtnActionPerformed
         EnterNumbers("9");
    }//GEN-LAST:event_ninebtnActionPerformed

    private void pluseminusbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pluseminusbtnActionPerformed
        double nums = Double.parseDouble(String.valueOf(jtxtResult.getText()));
        nums = nums * (-1);
        jtxtResult.setText(String.valueOf(nums));
    }//GEN-LAST:event_pluseminusbtnActionPerformed

    private void sevenbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sevenbtnActionPerformed
        EnterNumbers("7");
    }//GEN-LAST:event_sevenbtnActionPerformed

    private void eightbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eightbtnActionPerformed
         EnterNumbers("8");
    }//GEN-LAST:event_eightbtnActionPerformed

    private void fourbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourbtnActionPerformed
        EnterNumbers("4");
    }//GEN-LAST:event_fourbtnActionPerformed

    private void fivebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fivebtnActionPerformed
        EnterNumbers("5");
    }//GEN-LAST:event_fivebtnActionPerformed

    private void onebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onebtnActionPerformed
         EnterNumbers("1");
    }//GEN-LAST:event_onebtnActionPerformed

    private void twobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twobtnActionPerformed
         EnterNumbers("2");
    }//GEN-LAST:event_twobtnActionPerformed

    private void plusebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusebtnActionPerformed
       NumEnter1 = Double.parseDouble(jtxtResult.getText());
        jtxtResult.setText("");
        Op = "+";
    }//GEN-LAST:event_plusebtnActionPerformed

    private void minusbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minusbtnActionPerformed
        NumEnter1 = Double.parseDouble(jtxtResult.getText());
        jtxtResult.setText("");
        Op = "-";
    }//GEN-LAST:event_minusbtnActionPerformed

    private void pointbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pointbtnActionPerformed
         if(! jtxtResult.getText().contains("."))
         {
             jtxtResult.setText(jtxtResult.getText() + pointbtn.getText());
         }
    }//GEN-LAST:event_pointbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbtn;
    private javax.swing.JButton cbtn;
    private javax.swing.JButton cebtn;
    private javax.swing.JButton dividedbtn;
    private javax.swing.JButton eightbtn;
    private javax.swing.JButton equalbtn;
    private javax.swing.JButton fivebtn;
    private javax.swing.JButton fourbtn;
    private javax.swing.JTextField jtxtResult;
    private javax.swing.JButton minusbtn;
    private javax.swing.JButton multibtn;
    private javax.swing.JButton ninebtn;
    private javax.swing.JButton onebtn;
    private javax.swing.JButton plusebtn;
    private javax.swing.JButton pluseminusbtn;
    private javax.swing.JButton pointbtn;
    private javax.swing.JButton sevenbtn;
    private javax.swing.JButton sixbtn;
    private javax.swing.JButton threebtn;
    private javax.swing.JButton twobtn;
    private javax.swing.JButton zerobtn;
    // End of variables declaration//GEN-END:variables
}
